package com.pentasys.ws.java4web.common;

public enum ErrorCode {
    UNEXPECTED_ERROR,
    VAL_MANDATORY_ATTRIBUTE_NULL, 
    VAL_ATTRIBUT_FORMAT_ERROR, 
    VAL_DATE_IN_FUTURE, 
    VAL_DATE_IN_PAST, 
    VAL_CONDITIONAL_MANDATORY_ATTRIBUTE_NULL, 
    VAL_NOT_A_VALID_TIMESPAN, 
    ATTRIBUT_VALUE_ERROR, 
    CREATE_WITH_ID, 
    UPDATE_WITHOUT_ID, 
    IO_ERROR, 
    UNSUPPORTED_ENCODING, 
    NOT_IMPLEMENTED, 
    REQUEST_DENIED, 
    CONCURRENT_MODIFICATION, 
    ILLEGAL_REQUEST, 
    KEY_NOT_FOUND, 
    NO_DATA, 
    EXTERNAL_SERVICE_ERROR, 
    EXTERNAL_SERVICE_TIMEOUT,
    VALIDATION_ERROR;

}
